// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package directcoupling;

@net.sf.jni4net.attributes.ClrType
public class Program extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected Program(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public Program() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        directcoupling.Program.__ctorProgram0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorProgram0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)LMicrosoft/CodeAnalysis/Compilation;")
    public native static system.Object CreateTestCompilation(java.lang.String path);
    
    public static system.Type typeof() {
        return directcoupling.Program.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        directcoupling.Program.staticType = staticType;
    }
    //</generated-proxy>
}
